import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { useState } from 'react';
import Chart from '../components/Chart';

export default function Home() {
  const [data, setdata] = useState([]);
  const [pace, setpace] = useState('');
  const [cadence, setcadence] = useState('');
  const [distance, setdistance] = useState('');

  function getdata() {
    return data;
  }

  //let dataplot;
  //console.log(data);
  // if (data.length > 0) {
  //   dataplot = ;
  // }
  // else {
  //   dataplot = <div></div>;
  // }

  return (
    <div className={styles.container}>
      <Head>
        <title>Talaria Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.page}>
        <h1>Talaria</h1>
        <div>
          <label>
            Pace:
            <input type="text" name="pace" value={pace} onChange={(e) => {setpace(e.target.value)}}/>
          </label>
          <label>
            Cadence:
            <input type="text" name="cadence" value={cadence} onChange={(e) => {setcadence(e.target.value)}}/>
          </label>
          <label>
            Distance:
            <input type="text" name="distance" value={distance} onChange={(e) => {setdistance(e.target.value)}}/>
          </label>
          <input type="submit" value="Submit" onClick={ async () => {
            const response = await fetch('api/log_data', {
              method: 'POST', 
              body: JSON.stringify({pace: pace, cadence: cadence, distance: distance}), 
              headers: {
                'Content-Type': 'application/json'
              },
            });
            const ndata = await response.json();
            //console.log(ndata);
            setdata(ndata);
            setpace('');
            setcadence('');
            setdistance('');
            }}/>
        </div>
        <div><Chart chartData={data} num_data={data.length}/></div>
      </main>
    </div>
  )
}